pine64-pinephonepro: kernel 6.4.7 -> 6.13.0
One patch could no longer be applied, so I recreated all three patches.

Also remove `BRCM_TRACING = yes;` from `devices/pine64-pinephonepro/kernel-config.nix` to fix:
```
ERROR: CONFIG_BRCM_TRACING is expected to be set to «CONFIG_BRCM_TRACING=y», but is not present in config file.
```
while running `bin/kernel-normalize-config pine64-pinephonepro`.